#!/usr/bin/env ruby

forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-lvm', '0.7.0'
mod 'puppetlabs-stdlib', '4.25.0'
mod 'puppetlabs-firewall', '1.11.0'
mod 'puppet-selinux', '1.5.1'
mod 'puppetlabs-postgresql', '5.12.1'
mod 'cmc-core',
  :git => 'git@github.com:ConclusionMC/puppet-core.git',
  :ref => 'v6.5.0'
mod 'puppet-puppetserver', '3.0.0'
mod 'puppetlabs-puppetdb', '6.0.2'
mod 'puppet-hiera', '3.0.0'
mod 'puppet-fw',
  :git => 'git@github.com:ConclusionMC/puppet-fw.git',
  :ref => 'v0.1.2'

mod 'puppetlabs-java', '1.5.0'
mod 'cmc-cis_linux',
  :git => 'git@github.com:ConclusionMC/puppet-cis_linux.git',
  :ref => 'v1.1.3'
mod 'elastic-elasticsearch', '6.3.1'
mod 'elastic-kibana', '6.3.0'
mod 'jfryman-nginx', '0.3.0'
mod 'elastic-logstash', '6.1.2'
mod 'yano3-cerebro', '0.2.0'
